# Generated by Django 4.0.4 on 2022-04-15 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWareHouse',
            fields=[
                ('WareHouseID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('x', models.BigIntegerField()),
                ('y', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('PackageID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('x', models.BigIntegerField()),
                ('y', models.BigIntegerField()),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('Status', models.CharField(choices=[('PROC', 'Processing'), ('PICK', 'Pickup'), ('DELI', 'Delivering'), ('DELD', 'Delivered')], default='PROC', max_length=100)),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('TruckID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('x', models.BigIntegerField()),
                ('y', models.BigIntegerField()),
                ('Status', models.CharField(choices=[('IDLE', 'Idle'), ('TRAVELING', 'Traveling'), ('ARRIVEWH', 'ArriveWarehouse'), ('LOADING', 'Loading'), ('DELIVERING', 'Delivering')], default='IDLE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeDstRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.BigIntegerField()),
                ('y', models.BigIntegerField()),
                ('PackageID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ups.package')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PickupWareHouseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.awarehouse')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='TicketID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_packages', to='ups.ticket'),
        ),
        migrations.AddField(
            model_name='package',
            name='TruckID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_packages', to='ups.ticket'),
        ),
    ]
