# Generated by Django 4.0.4 on 2022-04-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='beginProcess',
            field=models.BooleanField(default=False),
        ),
    ]
