# Generated by Django 4.0.4 on 2022-04-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='PackageID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='truck',
            name='TruckID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
